Numpy
Assignment Questions











Q1:- What is a Python library? Why ^o we use Python libraries?

In [11]:
import numpy as np
m1=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
arr = np.array(m1)
print(arr.ndim)

2


In [13]:
import numpy as np
arr = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

first_row = arr[0]
print(first_row)

[1, 2, 3, 4]


In [21]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print(arr[2,3]) #third row and fouth column

12


In [2]:
import numpy as np 
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

odd_element = arr[:,1::2]
print(odd_element)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [3]:
import numpy as np
import random

matrix = np.random.rand(3,3)
print(matrix
     )

[[0.42940393 0.50390576 0.9071131 ]
 [0.85670144 0.93987945 0.11849994]
 [0.33088073 0.02056893 0.11492711]]


In [8]:
import numpy as np
#original array
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

#increase dimension along axis 0 
new_array = np.expand_dims(arr, axis = 0)
print(new_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [10]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

transpose_array = np.transpose(arr)
print(transpose_array)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [12]:
#==> 1.Index wise multiplication

A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
)
B2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

result = np.multiply(A2,B2)
print(result)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [14]:
#==> 2.Matrix Multiplication
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
)
B2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

result = np.dot(A2, B2.T) # Or equivalently, result = A2 @ B2.T
print("Resul of the matrix Multiplication:-", result)

Resul of the matrix Multiplication:- [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [17]:
#==> Add both the matrics 
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
)
B2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
result = A2+B2
print(result)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [18]:
#==> Subtract matrix B from A
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
)
B2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

result = B2-A2
print(result)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [19]:
#==> Divide Matrix B by A.
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
)
B2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

result = B2/A2
print(result)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
Ans:==> 