Numpy
Assignment Questions










        
Q1:- What is a Python library? Why do we use Python libraries?

Ans:-A Python library is a collection of related modules. It contains bundles of code that can be used repeatedly in different programs. It makes Python Programming simpler and convenient for the programmer.

Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.


Q2:- What is the difference between Numpy array and List?

Ans:-  ==>Numpy arrays is a typed array, the array in memory stores a homogenous, densely packed numbers.


==> Python list is a heterogeneous list, the list in memory stores references to objects rather than the number themselves.

Q3:- Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [21]:
import numpy as np
m1=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
arr = np.array(m1)
print(arr.ndim)

2


Q4:- Write python code to access the first row of the following array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [22]:
import numpy as np
arr = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

first_row = arr[0]
print(first_row)

[1, 2, 3, 4]


Q5:- How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [23]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print(arr[2,3]) #third row and fouth column

12


Q6:- Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [24]:
import numpy as np 
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

odd_element = arr[:,1::2]
print(odd_element)

[[ 2  4]
 [ 6  8]
 [10 12]]


Q7:- How can you generate a random 3x3 matrix with values between 0 and 1?


In [25]:
import numpy as np
import random

matrix = np.random.rand(3,3)
print(matrix
     )

[[0.3600749  0.19988363 0.34663639]
 [0.28155165 0.23220914 0.10189759]
 [0.15008045 0.88023288 0.44818899]]


Q8:- Describe the difference between np.random.rand and np.random.randn?

Ans:- ==> np.random.rand and np.random.randn lies in the distribution of the generated numbers: uniform distribution for rand and standard normal distribution for randn.

Q9:- Write code to increase the dimension of the following array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [26]:
import numpy as np
#original array
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

#increase dimension along axis 0 
new_array = np.expand_dims(arr, axis = 0)
print(new_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


Q10:- How to transpose the following array in NumPy?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [27]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

transpose_array = np.transpose(arr)
print(transpose_array)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Q11:- Consider the following matrix:

Matrix A2 [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [28]:
#==> 1.Index wise multiplication

A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
)
B2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

result = np.multiply(A2,B2)
print(result)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [29]:
#==> 2.Matrix Multiplication
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
)
B2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

result = np.dot(A2, B2.T) # Or equivalently, result = A2 @ B2.T
print("Resul of the matrix Multiplication:-", result)

Resul of the matrix Multiplication:- [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [30]:
#==> Add both the matrics 
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
)
B2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
result = A2+B2
print(result)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [31]:
#==> Subtract matrix B from A
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
)
B2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

result = B2-A2
print(result)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [32]:
#==> Divide Matrix B by A.
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
)
B2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

result = B2/A2
print(result)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Q12:- Which function in Numpy can be used to swap the byte order of an array?

Ans: ==> Byteswap() function in Numpy is used to swap the byte order of  an Array. 

Q13:-  What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a square matrix. Specifically, if you have a square matrix A, the result of np.linalg.inv(A) will be another matrix B such that the product of A and B results in the identity matrix.

14. What does the np.reshape function do, and how is it used?

Ans:==> 
The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to rearrange the elements of an array into a new shape, as long as the total number of elements remains the same.

15. What is broadcasting in Numpy?

Ans:==> Broadcasting is a powerful mechanism in NumPy, a popular Python library for numerical computing, that allows arrays of different shapes to be combined together in arithmetic operations. When performing element-wise operations between arrays, NumPy compares their shapes element-wise, starting from the trailing dimensions and working its way forward. 